project_name: tikuAdapter
builds:
  - main: ./cmd/adapter-service
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
    ldflags: -s -w
checksum:
  name_template: checksums.txt
