project_name: tikuAdapter
builds:
  - main: ./cmd/adapter-service
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: '-extldflags "-static"'
checksum:
  name_template: checksums.txt
