project_name: tikuAdapter
builds:
  - main: ./cmd/adapter-service
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: "-s -w -extldflags '-static'"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
checksum:
  name_template: checksums.txt
