limit:
  enable: false # 是否开启
  duration: 3  # 时间窗口为3秒
  requests: 1  # 允许用户在3秒内通过1个请求
api:
  - name: '样例接口 json 请求'
    enable: false
    url: http://lyck6.cn/scriptService/api/autoFreeAnswer
    method: POST
    headers:
      - key: Content-Type
        value: application/json
    body: '{"question":"${question}"}'
    answer: 'result.answers.0.0'

  - name: '样例接口 表单请求'
    enable: false
    url: https://cx.icodef.com/wyn-nb?v=4
    method: POST
    headers:
      - key: Content-Type
        value: application/x-www-form-urlencoded
    body: 'question=${question}'
    answer: 'data'
elasticsearch:
  url: http://127.0.0.1:9200